import Head from 'next/head';
import Header from '../components/Header';
import styles from '../styles/Home.module.scss';
import Title from '../components/Title';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header isHome={true} />
            <main>
                <Title title="مسیر خود را انتخاب کنید !" />
            </main>
        </>
    );
}
